### ISSUE TITLE
Hit & Bust

### ISSUE THREAD

**Issue by brynertoma** [jenniee/BlackjackJbm#3]
**BEFORE HAND**
Bet amount: 1000
Previous win: 0
Balance: 1000

---------- > **HIT**

**AFTER HAND** - BUST
Bet Amount: 1000
Previous win: 0
Balance: 0

**EXPECTED** - BUST
Bet Amount: 0
Previous win: 0
Balance: 0

**Comment by kepoly** [comment]
Fixed see merge: https://github.com/jenniee/BlackjackJbm/commit/9ba1da241bf362cd91deff4f35db5a30f37f6fc3
