### ISSUE TITLE
No reset button

### ISSUE THREAD

**Issue by brynertoma** [jenniee/BlackjackJbm#4]
**BEFORE HAND**
Bet amount: 1000
Previous win: 0
Balance: 1000

---------- > **HIT**

**AFTER HAND** - BUST
Bet Amount: 1000
Previous win: 0
Balance: 0

**EXPECTED** - BUST
Bet Amount: 0
Previous win: 0
Balance: 0
**RESET BUTTON TO REFILL CHIPS**

**Comment by kepoly** [comment]
Duplicate issue
